dist: trusty
sudo: false
language: c

matrix:
   include:
       - os: linux
         arch: amd64
         compiler: clang
       - os: linux
         arch: ppc64le
         compiler: clang
       - os: osx
         arch: amd64
         compiler: clang
       - os: linux
         arch: amd64
         compiler: gcc 
       - os: linux
         arch: ppc64le
         compiler: gcc 
       - os: osx
         arch: amd64
         compiler: gcc 
script: make && make check
jobs:
  include:
    - stage: Acceptance Test
      language: ruby
      rvm: 2.5.1
      script: make acceptance
      addons:
        apt:
          packages:
          - tmux
